; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:esp32-32e]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
lib_deps = 
    bodmer/TFT_eSPI @ ^2.5.43
   esphome/ESP32-audioI2S @ ^2.0.7
   bitbank2/PNGdec

build_flags =
  -D USER_SETUP_LOADED=1
  -D ST7796_DRIVER=1
  -D TFT_WIDTH=320
  -D TFT_HEIGHT=480
  -D TFT_MISO=12 ; Formerly 12, 19
  -D TFT_MOSI=13 ; Formerly 13, 23
  -D TFT_SCLK=14 ; Formerly 14
  -D TFT_CS=15 
  -D TFT_DC=2 ; Formerly 22
  -D TOUCH_CS=33
  -D TOUCH_IRQ=36
  -D TFT_RST=-1 ; (Formerly 12,4)
  -D TFT_BL=27
  ;-D TFT_BACKLIGHT_ON=HIGH
  -D SPI_FREQUENCY=27000000 ; Lower from default (typically 40MHz or 80MHz)


monitor_dtr = 1
monitor_rts = 1